// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'checkbox': string;
  'counter': string;
  'custom_check': string;
  'delete': string;
  'edit': string;
  'edit_label': string;
  'label': string;
  'next': string;
  'root': string;
  'run': string;
  'settings': string;
  'stop': string;
}
export const cssExports: CssExports;
export default cssExports;
