// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'header': string;
  'root': string;
  'taskBox': string;
}
export const cssExports: CssExports;
export default cssExports;
