// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'root': string;
  'smallInput': string;
  'textInput': string;
}
export const cssExports: CssExports;
export default cssExports;
