// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'filter': string;
  'focused': string;
  'list': string;
  'no_tasks': string;
  'not_focused': string;
  'root': string;
}
export const cssExports: CssExports;
export default cssExports;
